//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeackWorks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPicture
    {
        public int Id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public byte[] PhotoOrder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
